/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jh_mylibrary_NdkString */

#ifndef _Included_com_jh_mylibrary_NdkString
#define _Included_com_jh_mylibrary_NdkString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jh_mylibrary_NdkString
 * Method:    getFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jh_mylibrary_NdkString_getFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
